specs:
  - Production details
  - Production status
  - Original name
  - System
  - Speed
  - Focal length
  - Lens construction
  - Focusing modes
  - Number of blades
  - Optical design
  - Closest focusing distance
  - Maximum magnification
  - Weight
  - Filters
